# Pruning Types
STRUCTURED_PRUNING = "STRUCTURED_PRUNING"
UNSTRUCTURED_PRUNING = "UNSTRUCTURED_PRUNING"
BLOCK_PRUNING = "BLOCK_PRUNING"

# Module type
LINEAR = "LINEAR"
CONV2D = "CONV2D"

# Default Pruning Configs
ST_DEFAULT_PARAMS = {}
